README.md
=> Update README.md LICENSE

happi-graph.js
=> Comment width height, quickfix

demo/index.html, happi-graph.js
=> Fix graph initial data load

happi-graph-legend.js, happi-graph.js
=> Add graph custom styling for links

happi-graph.js, package-lock.json, package.json
=> Fix missing type being passed around

happi-graph-algorithms.js, happi-graph-helpers.js
=> Add docs on algorithm and update PROPERTY_MAX_LENGTH to 14

happi-graph-algorithms.js
=> Revert: Update happi-graph-algorithms.js

demo/index.html, happi-graph-legend.js, happi-graph.js, package-lock.json, package.json
=> Add a new clean ELK and VISJS algorithm for rendering graphs

happi-graph.js
=> Change direction for VISJS

happi-graph.js
=> Set VISJS as default algorithm

happi-graph-helpers.js
=> Change PROPERTY_MAX_LENGTH

package-lock.json
Signed-off-by: Marius Patrascu <marius-florin.patrascu@ing.com>
=> updated package lock

happi-graph.js
=> Use ELK on horizontal, VISJS on vertical and add async details

happi-graph.js
=> Add .min.js

package-lock.json, package.json
=> Bump egeria-js-commons version to v0.2.1

happi-graph-legend.js
Signed-off-by: Marius Patrascu <marius-florin.patrascu@ing.com>
=> fix exception 

package-lock.json, package.json
=> Bump version to 2.11.0

demo/index.html, happi-graph.js
=> Implement custom zooming level defined by number of nodes

happi-graph.js, package-lock.json, package.json
=> Extract nodeDistance on x, y coords to external properties

demo/index.html, happi-graph-helpers.js, happi-graph-helpers.test.js
=> Update anchor points for bottom linked nodes

happi-graph.js
=> Limit node movement only on the X axis for vertical lineage

happi-graph-helpers.js, happi-graph.js
Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>
=> Added click event on graph links (edges)

package-lock.json, package.json, src/components/App/index.tsx, src/components/HappiGraph/happi-graph-legend.component.tsx, src/components/HappiGraph/happi-graph.component.tsx, src/index.tsx
=> Hide console.log via debug prop parameter

docs/_config.yml
=> Fix config

docs/_sass/support/_variables.scss
=> Update main color

docs/_sass/support/_variables.scss
=> Update colors in _variables.scss

docs/_sass/support/_variables.scss
=> Update button color in docs

.gitignore, README.md, package-lock.json, package.json, src/components/App/index.tsx, src/components/HappiGraph/happi-graph.component.tsx
Signed-off-by: Iliescu Cristian-Mihai <cristianmihaiiliescu@gmail.com>
=> Added print mode for lineage

README.md, package-lock.json, package.json, src/components/App/index.tsx, src/components/HappiGraph/happi-graph.component.tsx, src/components/HappiGraph/happi-graph.render.ts
Signed-off-by: Iliescu Cristian-Mihai <cristianmihaiiliescu@gmail.com>
=> added onGraphRender handler

package-lock.json, package.json
=> Revert "Bump @types/uuid from 8.3.4 to 9.0.0"
